Algoritmo "semnome"

Var
a, b, c, areaA, areaB, areaC: real



Inicio
escreva ("digite a medida A: ")
leia (a)
escreva("digite a medida B: ")
leia (b)
escreva ("digite a medida C: ")
leia (c)

AreaA <- a * A
AreaB <- b * 2
AreaC <- ((A + B) * C / 2)

ESCREVAL ("AREA DO QUUADRADO= ", AREAA:3:4)
ESCREVAL ("AREA DO TRIANGULO= ", AREAB:3:4)
ESCREVAL ("AREA DO TRAPEZIO= ", AREAC:3:4)



Fimalgoritmo