Algoritmo "semnome"

Var
a, b, c , MENOR: INTEIRO








Inicio
ESCREVA ("DIGITE O PRIMEIRO VALOR: ")
LEIA (a)
ESCREVA ("DIGITE O SEGUNDO VALOR: ")
LEIA (b)
ESCREVA ("DIGITE O TERCEIRO VALOR: ")
leia (c)

se (a < b) e (a < c) entao
   menor <- a

senao
    se b < c entao
    menor <- b
      senao
         menor <- c


      fimse
    fimse
    
    escreval ("menor = ", menor )












Fimalgoritmo